### PR TITLE
Refactor `DocuSignObject` and tests

### PR DESCRIPTION
**Pull request by kbussell**
Implements #74 

This change makes serializable objects more flexible and less verbose.
Tests have been moved to a tests directory to remove visual clutter from the code.

Requesting feedback to know if this is easier for people to use and extend from.

### CODE REVIEW

**Comment by zebuline** [comment]
@kbussell can you rebase this PR please ?

**Comment by kbussell** [comment]
Gah. That's all broken. Please hold...

**Comment by kbussell** [comment]
Ok, sorry for all the interim craziness. That rebase was more painful than it should have been.

Anyway, what do you think of the changes? I wanted to make it simpler to add/manage the serialization objects.

**Comment by zebuline** [comment]
Sorry for the delay @kbussell I was in vacations.
These changes are ok for me, I like simplifications :)

**Comment by zebuline** [comment]
@kbussell this PR seems not to be python 3 compliant :/

**Comment by kbussell** [comment]
Sorry about that!

**Comment by zebuline** [comment]
It works, thanks for your work @kbussell

**Pull request merged**
