### PR TITLE
Add support for creating envelope with multiple documents #66

### PR DESCRIPTION
**Pull request by moiseshiraldo**

### CODE REVIEW

**Comment by zebuline** [comment]
@moiseshiraldo the code to create an envelope has changed (`pycurl` replaced by `requests`); you can update your PR if you want.

**Comment by zebuline** [comment]
@moiseshiraldo the tests are in failure :/

By the way, I think the method `create_envelope_from_document` has a wrong name, if it works with more than one document. May be it can be renamed into `create_envelope_from_documents` (with compatibility for the old method, and a deprecation warning) ?
And the test `demo/embeddedsigning.py` can be improved with 2 documents.

**Comment by zebuline** [comment]
@moiseshiraldo still failing: the second time the file obj is empty, as it was already read.

**Comment by zebuline** [comment]
Note: you can ping me when you do a change, so I can react more quickly

**Comment by moiseshiraldo** [comment]
@zebuline Sorry, I did last commit in a rush and I'm having some problems running the test suite on my local machine. I've added another test file and fix the empty object problem. Also, let me know if you wanna change anything about the deprecation message for the `create_envelope_from_document` method.

**Comment by zebuline** [comment]
@moiseshiraldo no problem :)
It looks fine, thank you for your work !

**Pull request merged**
