### PR TITLE
fixes #96 by expecting a 201 response code

### LINKED ISSUE #96: unexpected status code returned for DocuSignClient.add_envelope_recipients
Apparently, an `add_envelope_recipients` request returns a 201 response [edit: _in v2 of the API_] , yet the client is expecting a 200.  An exception is raised:

`DocuSignException: DocuSign request failed: POST https://demo.docusign.net/restapi/v2/accounts/<account>/envelopes/<envelope>/recipients returned code 201 while expecting code 200; Message: {...}`

Should we be setting `expected_status_code=201` in just the `post` for that method, or should we set that in the `post` method itself?

### PR DESCRIPTION
**Pull request by smcoll**
fixes #96

### CODE REVIEW

**Comment by zebuline** [comment]
I'm not sure about this fix.

APIv1: https://www.docusign.com/p/RESTAPIGuide/RESTAPIGuide.htm#REST%20API%20References/Add%20Recipients%20to%20an%20Envelope.htm%3FTocPath%3DREST%2520API%2520References%7C_____78
the status_code is supposed to be 200
APiv2: https://docs.docusign.com/esign/restapi/Envelopes/EnvelopeRecipients/create/
201

In fact pydocusign was written for apiv1, and is not yet compatible with v2. But, some docstring link the apiv2 documentation.

**Comment by smcoll** [comment]
Oh, you're right... that is a problem.  Given the pending deprecation of the v1 API, what is the strategy/timeline for supporting v2?

**Comment by zebuline** [comment]
We should migrate to the v2, that's sure. But right now I don't have time for that. If you do, feel free to propose a pull request :)

**Comment by zebuline** [comment]
Ok, little update: the old api reference (https://www.docusign.com/p/RESTAPIGuide/RESTAPIGuide.htm) seems to be apiv2 compliant, but the status_code mentioned for the endpoint "Add one or more recipients to an envelope" is wrong.

I prepare a PR to mention only the new api reference (https://docs.docusign.com/esign/), and I will integrated your fix.

**Comment by zebuline** [comment]
closing in favor of #100

**Pull request closed without merging**
